import { BookOpen, Cross } from 'lucide-react';

export default function StatementOfFaith() {
  const articles = [
    {
      title: "The Scriptures",
      content: "We believe that the Holy Bible, consisting of the sixty-six books of the Old and New Testaments, is the inspired, infallible, and authoritative Word of God. It is the supreme and final authority in all matters of faith and practice."
    },
    {
      title: "God",
      content: "We believe in one God, eternally existing in three persons: Father, Son, and Holy Spirit. God is perfect in holiness, wisdom, power, and love. He is the Creator, Sustainer, and Ruler of the universe."
    },
    {
      title: "Jesus Christ",
      content: "We believe in the deity of Jesus Christ, His virgin birth, His sinless life, His substitutionary death on the cross, His bodily resurrection, His ascension to heaven, and His personal return in power and glory."
    },
    {
      title: "The Holy Spirit",
      content: "We believe in the personality and deity of the Holy Spirit. He convicts the world of sin, regenerates, baptizes, seals, and fills believers. He guides believers into all truth and empowers them for Christian living and service."
    },
    {
      title: "Man",
      content: "We believe that man was created in the image of God but fell into sin, resulting in total depravity. All humanity is therefore under God's wrath and condemnation, unable to save themselves."
    },
    {
      title: "Salvation",
      content: "We believe salvation is by grace alone, through faith alone, in Christ alone. It is entirely a work of God's grace, not dependent on human works. Salvation includes justification, regeneration, sanctification, and glorification."
    },
    {
      title: "The Church",
      content: "We believe the universal church consists of all who have been regenerated by the Holy Spirit. The local church is a congregation of baptized believers, organized to carry out the Great Commission under the authority of Scripture."
    },
    {
      title: "Baptism and Lord's Supper",
      content: "We believe in believer's baptism by immersion as a public declaration of faith in Christ. The Lord's Supper is a memorial ordinance for believers to remember Christ's death until He comes."
    },
    {
      title: "Last Things",
      content: "We believe in the personal return of Jesus Christ, the resurrection of the dead, the final judgment, and the eternal state of the saved and lost. We believe in the new heavens and new earth."
    }
  ];

  return (
    <div>
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-blue-900 to-blue-800 text-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="w-20 h-20 bg-blue-600 rounded-full flex items-center justify-center mx-auto mb-6">
              <BookOpen className="w-10 h-10 text-white" />
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-6">Statement of Faith</h1>
            <p className="text-xl md:text-2xl text-blue-100 max-w-3xl mx-auto">
              Our foundational beliefs based on the authoritative Word of God
            </p>
          </div>
        </div>
      </section>

      {/* Introduction */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">
              Grounded in Scripture
            </h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              As a Reformed Baptist church, we hold to the historic Christian faith as
              recovered during the Protestant Reformation. Our statement of faith reflects
              our commitment to the authority of Scripture and the sovereignty of God in salvation.
            </p>
          </div>

          <div className="bg-blue-50 border-l-4 border-blue-600 p-6 mb-12">
            <div className="flex items-start">
              <Cross className="w-6 h-6 text-blue-600 mt-1 mr-3 flex-shrink-0" />
              <div>
                <h3 className="text-lg font-semibold text-blue-900 mb-2">
                  The Five Solas
                </h3>
                <p className="text-blue-800">
                  We affirm the five foundational principles of the Reformation:
                  Scripture Alone, Grace Alone, Faith Alone, Christ Alone, and Glory to God Alone.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Articles of Faith */}
      <section className="py-16 bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Articles of Faith
            </h2>
            <p className="text-lg text-gray-600">
              What we believe about the essential doctrines of the Christian faith
            </p>
          </div>

          <div className="space-y-8">
            {articles.map((article, index) => (
              <div key={index} className="bg-white rounded-lg shadow-lg p-8">
                <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3">
                    {index + 1}
                  </span>
                  {article.title}
                </h3>
                <p className="text-gray-700 leading-relaxed">
                  {article.content}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Confessional Standards */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">
              Confessional Standards
            </h2>
            <p className="text-lg text-gray-600 mb-8">
              In addition to our statement of faith, we also affirm historic Reformed confessions
              that have faithfully summarized biblical teaching throughout church history.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="bg-gray-50 p-8 rounded-lg">
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                1689 London Baptist Confession
              </h3>
              <p className="text-gray-700">
                We hold to the Second London Baptist Confession of Faith (1689) as a
                faithful summary of biblical doctrine, particularly as it relates to
                Baptist distinctives and Reformed theology.
              </p>
            </div>

            <div className="bg-gray-50 p-8 rounded-lg">
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                Abstract of Principles
              </h3>
              <p className="text-gray-700">
                We also find the Abstract of Principles to be a helpful and concise
                statement of Reformed Baptist doctrine that aligns with our biblical convictions.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action */}
      <section className="py-16 bg-blue-900 text-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Questions About Our Beliefs?
          </h2>
          <p className="text-xl mb-8 text-blue-100">
            We welcome discussion about our doctrinal positions and would be happy
            to answer any questions you may have.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="/contact"
              className="bg-white text-blue-900 hover:bg-gray-100 px-8 py-3 rounded-lg font-semibold transition-colors"
            >
              Contact Us
            </a>
            <a
              href="/about/our-beliefs"
              className="border border-white text-white hover:bg-white hover:text-blue-900 px-8 py-3 rounded-lg font-semibold transition-colors"
            >
              Our Beliefs
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}
